### ISSUE TITLE
Is the private key required to send a message in E-2-E mode?

### ISSUE THREAD

**Issue by holzhannes** [threema-ch/threema-msgapi-sdk-php#2]
In case I like to use a web server to send Threema messages to a phone/ID is my private key required to send a message in E-2-E mode? It is not a nice feeling having the private key on the server. Do you use the private key for signing the message?

**Comment by medienverbinder** [comment]
Yes, for E-2-E mode you need the private key.

=> https://gateway.threema.ch/de/developer/api

################
End-to-end encrypted mode
-  The server doesn't know your private key.
-  Incoming messages and delivery receipts are supported.
-  You need to run software on your side to encrypt each message before it can be sent, and to decrypt any incoming messages or delivery receipts.
################

If you do not want to put the (plain) secret key to server, you could use AES for example to encrypt the secret key.

**Comment by lgrahl** [comment]
You could use an encrypted file system if you don't host the server yourself. But the private key would still be accessible in RAM. As all languages that have an implementation for the Threema Message API are garbage collected, there is no real way of knowing when the private key has been garbage collected. Moreover, there is a decent chance that the private key remains in RAM after the language runtime exits. I wouldn't be too concerned about RAM because you've pretty much lost if an attacker has read access to it.
